import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from datasets import CONFIG, DATASETS

PKG = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(PKG, "config")


def read_anchor_file(path, n):
    vals = []
    with open(path) as fh:
        for line in fh:
            line = line.split("#")[0].strip()
            if not line:
                continue
            xyz = [float(v) for v in line.split()]
            if len(xyz) >= 3:
                vals.append(xyz[:3])
            if len(vals) == n:
                break
    return vals


def params_for(dataset):
    ds = CONFIG[dataset]
    seq = ds["sequences"][0]

    per_seq_init = {}
    if dataset == "iului":
        meta = json.load(open(os.path.join(PKG, ds["meta"].format(seq=seq))))
        anchors = meta["anchors"]
        tag_offsets = [meta["tag0_offset"], meta["tag1_offset"]]
        anchor_ids = list(range(len(anchors)))
        init = meta["init"]
        for s2 in ds["sequences"]:
            m2 = json.load(open(os.path.join(PKG, ds["meta"].format(seq=s2))))
            per_seq_init[s2] = m2["init"]
    else:
        n = 6 if dataset == "miluv" else 3
        anchors = read_anchor_file(os.path.join(PKG, ds["anchor_file"]), n)
        tag_offsets = ds["tag_offsets"]
        anchor_ids = ds.get("anchor_ids", list(range(n)))
        init = ds.get("init", [0.0, 0.0, 0.0])

    return dict(dataset=dataset, num_anchors=len(anchors), tag_ids=ds["tag_ids"],
                anchor_ids=anchor_ids, per_seq_init=per_seq_init,
                anchors=[v for a in anchors for v in a],
                tag_offsets=[v for t in tag_offsets for v in t],
                init=list(init))


def fmt(v):
    if isinstance(v, list):
        return "[" + ", ".join(fmt(x) for x in v) + "]"
    if isinstance(v, float):
        return f"{v:.6f}"
    if isinstance(v, str):
        return f'"{v}"'
    return str(v)


def main():
    os.makedirs(OUT, exist_ok=True)
    for dataset in DATASETS:
        p = params_for(dataset)
        path = os.path.join(OUT, f"online_{dataset}.yaml")
        with open(path, "w") as fh:
            fh.write(f"# Deployment parameters for the {dataset} setup.\n")
            fh.write("# Generated by scripts/make_online_params.py from the dataset files.\n")
            fh.write("# Estimator settings are NOT here: they are compiled in, see include/presets.h.\n")
            for k in ("dataset", "num_anchors", "tag_ids", "anchor_ids"):
                fh.write(f"{k}: {fmt(p[k])}\n")
            fh.write("# anchor survey, x y z per anchor, in anchor-id order\n")
            fh.write(f"anchors: {fmt(p['anchors'])}\n")
            fh.write("# tag lever arms in the body frame, x y z per tag\n")
            fh.write(f"tag_offsets: {fmt(p['tag_offsets'])}\n")
            fh.write(f"init: {fmt(p['init'])}\n")
            for seq_name, v in p["per_seq_init"].items():
                fh.write(f"init_{seq_name}: {fmt(list(v))}\n")
        print(f"  wrote {path}  ({p['num_anchors']} anchors, {len(p['tag_ids'])} tags)")


if __name__ == "__main__":
    main()
